"""Plugin interface: registry, image-tag hashing, and Dockerfile rendering."""

from __future__ import annotations

import pytest

from glove import plugins
from glove.config import Config, Service, _coerce
from glove.harness import effective_image, get_profile
from glove.plugins import ALL_HARNESSES, ImageLayer, Plugin, resolve_plugins
from glove.plugins.image import render_dockerfile, stage_context


@pytest.fixture
def fake_registry(monkeypatch):
    """Swap in a throwaway registry so tests don't depend on shipped plugins."""
    reg: dict[str, Plugin] = {}
    monkeypatch.setattr(plugins, "_REGISTRY", reg)
    return reg


def _media() -> Plugin:
    return Plugin(
        name="media",
        summary="media/analysis toolchain",
        image={
            ALL_HARNESSES: ImageLayer(apt=("ffmpeg", "imagemagick")),
            "vibe": ImageLayer(pip=("Pillow",)),
            "pi": ImageLayer(npm=("some-cli",)),
        },
    )


# --- image tag hashing -----------------------------------------------------

def test_effective_image_no_extras_is_base():
    profile = get_profile("vibe")
    assert effective_image(profile) == profile.image
    assert effective_image(profile, [], [], []) == profile.image


def test_effective_image_plugins_hashed_and_distinct():
    profile = get_profile("vibe")
    a = effective_image(profile, plugins=["media"])
    b = effective_image(profile, plugins=["browser"])
    ab = effective_image(profile, plugins=["media", "browser"])
    assert a != profile.image and a != b and a != ab
    # Order-independent: same set → same tag.
    assert effective_image(profile, plugins=["browser", "media"]) == ab
    assert all(t.startswith(profile.image + "-") for t in (a, b, ab))


def test_effective_image_plugins_and_pkgs_combine():
    profile = get_profile("vibe")
    only_plugins = effective_image(profile, plugins=["media"])
    with_pip = effective_image(profile, pip_packages=["rich"], plugins=["media"])
    assert only_plugins != with_pip


# --- registry --------------------------------------------------------------

def test_resolve_unknown_plugin_raises(fake_registry):
    with pytest.raises(ValueError, match="unknown plugin 'nope'"):
        resolve_plugins(["nope"])


def test_resolve_dedupes_preserving_order(fake_registry):
    fake_registry["media"] = _media()
    fake_registry["x"] = Plugin(name="x", summary="x")
    out = resolve_plugins(["x", "media", "x"])
    assert [p.name for p in out] == ["x", "media"]


def test_register_rejects_duplicate(fake_registry):
    plugins.register(_media())
    with pytest.raises(ValueError, match="already registered"):
        plugins.register(_media())


# --- layers + dockerfile rendering -----------------------------------------

def test_layers_for_shared_then_specific():
    layers = _media().layers_for("vibe")
    assert layers[0].apt == ("ffmpeg", "imagemagick")  # shared first
    assert layers[1].pip == ("Pillow",)  # harness-specific second


def test_render_dockerfile_vibe_apt_and_pip():
    profile = get_profile("vibe")
    df = render_dockerfile(profile.image, profile, [_media()])
    assert df.startswith("# Generated by glove")
    assert f"FROM {profile.image}" in df
    assert "apt-get install -y --no-install-recommends ffmpeg imagemagick" in df
    # Vibe installs pip via its uv command.
    assert "RUN uv pip install --system Pillow" in df
    assert "npm install" not in df  # pi-only layer excluded for vibe


def test_render_dockerfile_pi_npm_only():
    profile = get_profile("pi")
    df = render_dockerfile(profile.image, profile, [_media()])
    assert "RUN npm install -g some-cli" in df
    assert "Pillow" not in df  # vibe-only layer excluded for pi


def test_render_dockerfile_pip_without_installer_raises():
    profile = get_profile("pi")  # no pip_install
    plugin = Plugin(name="p", summary="", image={ALL_HARNESSES: ImageLayer(pip=("x",))})
    with pytest.raises(ValueError, match="no Python installer"):
        render_dockerfile(profile.image, profile, [plugin])


def test_render_dockerfile_copy_and_run():
    profile = get_profile("vibe")
    plugin = Plugin(
        name="p",
        summary="s",
        image={ALL_HARNESSES: ImageLayer(copy=(("/abs/host/foo.py", "/opt/glove/foo.py"),), run=("echo hi",))},
    )
    df = render_dockerfile(profile.image, profile, [plugin])
    assert "COPY foo.py /opt/glove/foo.py" in df  # staged under basename
    assert "RUN echo hi" in df


def test_stage_context_copies_sources(tmp_path):
    src = tmp_path / "foo.py"
    src.write_text("x = 1\n")
    dest = tmp_path / "ctx"
    dest.mkdir()
    profile = get_profile("vibe")
    plugin = Plugin(
        name="p", summary="s",
        image={ALL_HARNESSES: ImageLayer(copy=((str(src), "/opt/glove/foo.py"),))},
    )
    stage_context(dest, profile, [plugin])
    assert (dest / "foo.py").read_text() == "x = 1\n"


# --- config surface --------------------------------------------------------

def test_config_defaults_no_plugins():
    cfg = Config()
    assert cfg.plugins == []
    assert cfg.plugin_options == {}


def test_config_parses_plugins_list_and_options():
    cfg = _coerce({"plugins": ["media", "browser"], "plugin_options": {"browser": {"provider": "host-mcp"}}})
    assert cfg.plugins == ["media", "browser"]
    assert cfg.plugin_options["browser"]["provider"] == "host-mcp"


def test_config_parses_plugins_csv_string():
    cfg = _coerce({"plugins": "media, browser"})
    assert cfg.plugins == ["media", "browser"]


# --- shipped: media --------------------------------------------------------

def test_media_plugin_registered():
    assert "media" in plugins.known_plugins()
    assert resolve_plugins(["media"])[0].name == "media"


def test_search_pip_spec_is_shell_quoted():
    # `mcp<2` must be quoted or the shell reads `<2` as a redirection.
    search = plugins.get_plugin("search")
    df = render_dockerfile("base", get_profile("vibe"), [search])
    assert "uv pip install --system 'mcp<2'" in df
    assert "mcp<2 " not in df  # not left bare


def test_media_renders_shared_apt_and_per_harness():
    media = plugins.get_plugin("media")
    vibe_df = render_dockerfile("base", get_profile("vibe"), [media])
    assert "ffmpeg imagemagick webp libimage-exiftool-perl" in vibe_df
    assert "RUN uv pip install --system Pillow" in vibe_df
    assert "python3-pil" not in vibe_df  # pi-only

    pi_df = render_dockerfile("base", get_profile("pi"), [media])
    assert "ffmpeg imagemagick webp libimage-exiftool-perl" in pi_df
    assert "python3 python3-pil" in pi_df
    assert "Pillow" not in pi_df  # vibe-only


# --- shipped: search (plan-level wiring) -----------------------------------

def _search_cfg(tmp_path, harness):
    work = tmp_path / "wd"
    work.mkdir(exist_ok=True)
    cfg = Config(
        harness=harness, workdir=str(work), name="s",
        net=["service"], plugins=["search"],
    )
    cfg.services = [Service(name="search", to="searxng-host:8080", port=8080)]
    return cfg


def test_search_injects_searxng_url_env(tmp_path):
    from glove.plan import build_session_plan

    plan = build_session_plan(_search_cfg(tmp_path, "pi"), env_id="s", home_dir=str(tmp_path / "h"))
    assert plan.environment["SEARXNG_URL"] == "http://glove-s-search:8080"


def test_search_augments_pi_entry(tmp_path):
    from glove.plan import build_session_plan
    from glove.plugins.search import PI_EXTENSION_PATH

    plan = build_session_plan(_search_cfg(tmp_path, "pi"), env_id="s", home_dir=str(tmp_path / "h"))
    cmd = plan.harness_command
    assert "-e" in cmd and PI_EXTENSION_PATH in cmd
    # enforcer extension still loads too
    assert "/opt/glove/pi-extensions/enforcer" in cmd


def test_search_vibe_gets_mcp_not_pi_extension(tmp_path):
    from glove.harnessconfig import _mcp_servers
    from glove.plan import build_session_plan
    from glove.plugins.search import PI_EXTENSION_PATH

    cfg = _search_cfg(tmp_path, "vibe")
    plan = build_session_plan(cfg, env_id="s", home_dir=str(tmp_path / "h"))
    # Vibe uses MCP, not a `-e` extension.
    assert PI_EXTENSION_PATH not in plan.harness_command
    servers = _mcp_servers(cfg, "s")
    sx = next(s for s in servers if s["name"] == "searxng")
    assert sx["transport"] == "stdio"
    assert sx["env"]["SEARXNG_URL"] == "http://glove-s-search:8080"


def test_search_missing_service_errors(tmp_path):
    from glove.config import ConfigError
    from glove.plan import build_session_plan

    cfg = _search_cfg(tmp_path, "pi")
    cfg.services = []  # drop the required `search` service
    with pytest.raises(ConfigError, match="plugin 'search' requires service"):
        build_session_plan(cfg, env_id="s", home_dir=str(tmp_path / "h"))


# --- shipped: browser ------------------------------------------------------

def test_browser_plugin_registered():
    assert "browser" in plugins.known_plugins()


def _work(tmp_path):
    w = tmp_path / "wd"
    w.mkdir(exist_ok=True)
    return str(w)


def test_browser_legacy_block_enables_plugin_and_wires(tmp_path):
    # A legacy top-level `browser:` block implies the browser plugin, and
    # build_session_plan runs the provider wiring (service + host services).
    from glove.plan import build_session_plan
    from glove.plugins.browser import PI_EXTENSION_PATH

    cfg = Config(harness="pi", workdir=_work(tmp_path), name="s",
                 browser={"provider": "host-mcp", "port": 8931})
    plan = build_session_plan(cfg, env_id="s", home_dir=str(tmp_path / "h"))
    assert "browser" in cfg.plugins
    assert any(s.name == "browser" for s in cfg.services)
    assert {h.name for h in cfg.host_services} >= {"chrome", "playwright"}
    assert "service" in cfg.net  # provider enabled the forwarder path
    assert plan.environment["BROWSER_MCP_URL"] == "http://glove-s-browser:8931/mcp"
    assert PI_EXTENSION_PATH in plan.harness_command  # Pi loads the ext


def test_browser_via_plugins_list_defaults_host_mcp(tmp_path):
    from glove.plan import build_session_plan

    cfg = Config(harness="vibe", workdir=_work(tmp_path), name="s", plugins=["browser"])
    plan = build_session_plan(cfg, env_id="s", home_dir=str(tmp_path / "h"))
    # No provider given → defaults to host-mcp, which wires the browser service.
    assert cfg.browser.get("provider") == "host-mcp"
    assert any(s.name == "browser" for s in cfg.services)
    assert plan.environment["BROWSER_MCP_URL"].endswith("/mcp")


def test_browser_provider_none_skips_host_wiring(tmp_path):
    # provider: none → the plugin composes the ext/MCP but the operator hand-wires
    # host services (the pi-remote-llm pattern). No chrome host service auto-added.
    from glove.plan import build_session_plan
    from glove.plugins.browser import PI_EXTENSION_PATH

    cfg = Config(
        harness="pi", workdir=_work(tmp_path), name="s",
        net=["service"], plugins=["browser"],
        plugin_options={"browser": {"provider": "none"}},
    )
    cfg.services = [Service(name="browser", to="host.docker.internal:8931", port=8931)]
    plan = build_session_plan(cfg, env_id="s", home_dir=str(tmp_path / "h"))
    assert "chrome" not in {h.name for h in cfg.host_services}
    assert PI_EXTENSION_PATH in plan.harness_command  # ext still composed


# --- back-compat shim ------------------------------------------------------

def test_legacy_warnings_browser_block(tmp_path):
    from glove.plan import legacy_warnings

    cfg = Config(harness="vibe", workdir=_work(tmp_path), name="s",
                 browser={"provider": "host-mcp"})
    assert any("browser:" in w for w in legacy_warnings(cfg))
    # No warning once migrated to plugins.
    cfg2 = Config(harness="vibe", workdir=_work(tmp_path), name="s", plugins=["browser"])
    assert legacy_warnings(cfg2) == []


def test_legacy_warnings_search_service(tmp_path):
    from glove.plan import legacy_warnings

    cfg = Config(harness="pi", workdir=_work(tmp_path), name="s", net=["service"])
    cfg.services = [Service(name="search", to="x:8080", port=8080)]
    assert any("search" in w for w in legacy_warnings(cfg))
