"""Plugin interface: registry, image-tag hashing, and Dockerfile rendering."""

from __future__ import annotations

import pytest

from glove import plugins
from glove.config import Config, _coerce
from glove.harness import effective_image, get_profile
from glove.plugins import ALL_HARNESSES, ImageLayer, Plugin, resolve_plugins
from glove.plugins.image import render_dockerfile, stage_context


@pytest.fixture
def fake_registry(monkeypatch):
    """Swap in a throwaway registry so tests don't depend on shipped plugins."""
    reg: dict[str, Plugin] = {}
    monkeypatch.setattr(plugins, "_REGISTRY", reg)
    return reg


def _media() -> Plugin:
    return Plugin(
        name="media",
        summary="media/analysis toolchain",
        image={
            ALL_HARNESSES: ImageLayer(apt=("ffmpeg", "imagemagick")),
            "vibe": ImageLayer(pip=("Pillow",)),
            "pi": ImageLayer(npm=("some-cli",)),
        },
    )


# --- image tag hashing -----------------------------------------------------

def test_effective_image_no_extras_is_base():
    profile = get_profile("vibe")
    assert effective_image(profile) == profile.image
    assert effective_image(profile, [], [], []) == profile.image


def test_effective_image_plugins_hashed_and_distinct():
    profile = get_profile("vibe")
    a = effective_image(profile, plugins=["media"])
    b = effective_image(profile, plugins=["browser"])
    ab = effective_image(profile, plugins=["media", "browser"])
    assert a != profile.image and a != b and a != ab
    # Order-independent: same set → same tag.
    assert effective_image(profile, plugins=["browser", "media"]) == ab
    assert all(t.startswith(profile.image + "-") for t in (a, b, ab))


def test_effective_image_plugins_and_pkgs_combine():
    profile = get_profile("vibe")
    only_plugins = effective_image(profile, plugins=["media"])
    with_pip = effective_image(profile, pip_packages=["rich"], plugins=["media"])
    assert only_plugins != with_pip


# --- registry --------------------------------------------------------------

def test_resolve_unknown_plugin_raises(fake_registry):
    with pytest.raises(ValueError, match="unknown plugin 'nope'"):
        resolve_plugins(["nope"])


def test_resolve_dedupes_preserving_order(fake_registry):
    fake_registry["media"] = _media()
    fake_registry["x"] = Plugin(name="x", summary="x")
    out = resolve_plugins(["x", "media", "x"])
    assert [p.name for p in out] == ["x", "media"]


def test_register_rejects_duplicate(fake_registry):
    plugins.register(_media())
    with pytest.raises(ValueError, match="already registered"):
        plugins.register(_media())


# --- layers + dockerfile rendering -----------------------------------------

def test_layers_for_shared_then_specific():
    layers = _media().layers_for("vibe")
    assert layers[0].apt == ("ffmpeg", "imagemagick")  # shared first
    assert layers[1].pip == ("Pillow",)  # harness-specific second


def test_render_dockerfile_vibe_apt_and_pip():
    profile = get_profile("vibe")
    df = render_dockerfile(profile.image, profile, [_media()])
    assert df.startswith("# Generated by glove")
    assert f"FROM {profile.image}" in df
    assert "apt-get install -y --no-install-recommends ffmpeg imagemagick" in df
    # Vibe installs pip via its uv command.
    assert "RUN uv pip install --system Pillow" in df
    assert "npm install" not in df  # pi-only layer excluded for vibe


def test_render_dockerfile_pi_npm_only():
    profile = get_profile("pi")
    df = render_dockerfile(profile.image, profile, [_media()])
    assert "RUN npm install -g some-cli" in df
    assert "Pillow" not in df  # vibe-only layer excluded for pi


def test_render_dockerfile_pip_without_installer_raises():
    profile = get_profile("pi")  # no pip_install
    plugin = Plugin(name="p", summary="", image={ALL_HARNESSES: ImageLayer(pip=("x",))})
    with pytest.raises(ValueError, match="no Python installer"):
        render_dockerfile(profile.image, profile, [plugin])


def test_render_dockerfile_copy_and_run():
    profile = get_profile("vibe")
    plugin = Plugin(
        name="p",
        summary="s",
        image={ALL_HARNESSES: ImageLayer(copy=(("/abs/host/foo.py", "/opt/glove/foo.py"),), run=("echo hi",))},
    )
    df = render_dockerfile(profile.image, profile, [plugin])
    assert "COPY foo.py /opt/glove/foo.py" in df  # staged under basename
    assert "RUN echo hi" in df


def test_stage_context_copies_sources(tmp_path):
    src = tmp_path / "foo.py"
    src.write_text("x = 1\n")
    dest = tmp_path / "ctx"
    dest.mkdir()
    profile = get_profile("vibe")
    plugin = Plugin(
        name="p", summary="s",
        image={ALL_HARNESSES: ImageLayer(copy=((str(src), "/opt/glove/foo.py"),))},
    )
    stage_context(dest, profile, [plugin])
    assert (dest / "foo.py").read_text() == "x = 1\n"


# --- config surface --------------------------------------------------------

def test_config_defaults_no_plugins():
    cfg = Config()
    assert cfg.plugins == []
    assert cfg.plugin_options == {}


def test_config_parses_plugins_list_and_options():
    cfg = _coerce({"plugins": ["media", "browser"], "plugin_options": {"browser": {"provider": "host-mcp"}}})
    assert cfg.plugins == ["media", "browser"]
    assert cfg.plugin_options["browser"]["provider"] == "host-mcp"


def test_config_parses_plugins_csv_string():
    cfg = _coerce({"plugins": "media, browser"})
    assert cfg.plugins == ["media", "browser"]


# --- shipped: media --------------------------------------------------------

def test_media_plugin_registered():
    assert "media" in plugins.known_plugins()
    assert resolve_plugins(["media"])[0].name == "media"


def test_media_renders_shared_apt_and_per_harness():
    media = plugins.get_plugin("media")
    vibe_df = render_dockerfile("base", get_profile("vibe"), [media])
    assert "ffmpeg imagemagick webp libimage-exiftool-perl" in vibe_df
    assert "RUN uv pip install --system Pillow" in vibe_df
    assert "python3-pil" not in vibe_df  # pi-only

    pi_df = render_dockerfile("base", get_profile("pi"), [media])
    assert "ffmpeg imagemagick webp libimage-exiftool-perl" in pi_df
    assert "python3 python3-pil" in pi_df
    assert "Pillow" not in pi_df  # vibe-only
