"""`glove playwright view|status` — watch (or, when allowed, drive) a novnc browser.

`view` opens a loopback-only listener on a random port for as long as the
command runs. Each connection it accepts is checked (Host and Origin must be
this listener, so no other page in your browser, nor a DNS-rebinding one, can
use it) and then piped through `<runtime> exec -i <sidecar> socat` to
websockify on the sidecar's own loopback. Nothing is published and no port
outlives the command. The VNC password (generated by the sidecar at start, on
its tmpfs) is read into memory and handed to noVNC in the URL fragment, which
the browser never sends to a server.
"""

from __future__ import annotations

import asyncio
import contextlib
import subprocess
import webbrowser
from pathlib import Path

import typer
from rich.console import Console

from glove import sessiondir as sdm
from glove.naming import scoped

app = typer.Typer(add_completion=False, help="The playwright browser sidecar: watch or drive it (novnc).")
console = Console(highlight=False)
err = Console(stderr=True)

DIR_OPT = typer.Option(None, "--dir", help="session directory (default: the nearest one)")
WEBSOCKIFY = "TCP4:127.0.0.1:6080"
MAX_HEAD = 16384


def _fail(msg: str) -> typer.Exit:
    err.print(f"[red]error:[/red] {msg}")
    return typer.Exit(1)


def _session(directory: Path | None) -> tuple[str, str, dict]:
    """(runtime command, sidecar container, playwright settings as written)."""
    try:
        sd = sdm.find(directory)
        raw = sdm.load_file(sd)
    except sdm.SessionError as e:
        raise _fail(str(e)) from e
    sid = sd.read_id()
    if sid is None:
        raise _fail(f"{sd.root} has never been launched (no .glove/id)")
    pw = (raw.get("extensions") or {}).get("playwright")
    if not isinstance(pw, dict):
        raise _fail(f"{sd.file}: the playwright extension is not enabled")
    return sdm.session_provider(sd), scoped(sid, "pw"), pw


def _running(runtime: str, container: str) -> bool:
    r = subprocess.run([runtime, "inspect", "-f", "{{.State.Running}}", container], capture_output=True, text=True)
    return r.returncode == 0 and r.stdout.strip() == "true"


def allowed(head: bytes, port: int) -> bool:
    """A request may use the tunnel only if it names this listener as its Host
    and, when it carries an Origin (every WebSocket from a page does), comes
    from it too."""
    try:
        lines = head.decode("latin-1").split("\r\n")
    except UnicodeDecodeError:  # pragma: no cover - latin-1 decodes any bytes
        return False
    headers: dict[str, str] = {}
    for line in lines[1:]:
        k, sep, v = line.partition(":")
        if sep:
            headers.setdefault(k.strip().lower(), v.strip())
    me = f"127.0.0.1:{port}"
    if headers.get("host") != me:
        return False
    return "origin" not in headers or headers["origin"] == f"http://{me}"


def view_url(port: int, password: str, *, control: bool) -> str:
    """noVNC's URL: every setting, the password included, in the fragment."""
    return (f"http://127.0.0.1:{port}/vnc.html#autoconnect=1&resize=scale&reconnect=1"
            f"&view_only={0 if control else 1}&password={password}")


async def _pipe(reader: asyncio.StreamReader, writer) -> None:
    try:
        while data := await reader.read(65536):
            writer.write(data)
            await writer.drain()
    except (ConnectionError, BrokenPipeError):
        pass
    finally:
        with contextlib.suppress(Exception):  # best effort, either side may be gone
            writer.close()


async def _serve(runtime: str, container: str, password: str, *, control: bool, open_browser: bool) -> None:
    port = 0

    async def handle(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
        try:
            head = await reader.readuntil(b"\r\n\r\n")
        except (asyncio.IncompleteReadError, asyncio.LimitOverrunError):
            writer.close()
            return
        if not allowed(head, port):
            writer.write(b"HTTP/1.1 403 Forbidden\r\nContent-Length: 0\r\nConnection: close\r\n\r\n")
            await writer.drain()
            writer.close()
            return
        proc = await asyncio.create_subprocess_exec(
            runtime, "exec", "-i", container, "socat", "STDIO", WEBSOCKIFY,
            stdin=asyncio.subprocess.PIPE, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL)
        assert proc.stdin is not None and proc.stdout is not None
        proc.stdin.write(head)
        await asyncio.gather(_pipe(reader, proc.stdin), _pipe(proc.stdout, writer))
        if proc.returncode is None:
            proc.kill()
        await proc.wait()

    server = await asyncio.start_server(handle, "127.0.0.1", 0, limit=MAX_HEAD)
    port = server.sockets[0].getsockname()[1]
    url = view_url(port, password, control=control)
    console.print(f"[bold]{'controlling' if control else 'watching'}[/bold] {container} on "
                  f"http://127.0.0.1:{port}/ (loopback only; Ctrl-C closes it)")
    if open_browser:
        webbrowser.open(url)
    else:
        console.print(f"open: {url}", soft_wrap=True)
    async with server:
        await server.serve_forever()


@app.command("view")
def view(
    directory: Path | None = DIR_OPT,
    control: bool = typer.Option(False, "--control", help="take control (needs allow_control: true)"),
    no_open: bool = typer.Option(False, "--no-open", help="print the URL instead of opening it"),
) -> None:
    """Watch the novnc browser in your own browser, through a transient loopback tunnel."""
    runtime, container, pw = _session(directory)
    if pw.get("mode") != "novnc":
        raise _fail("`view` needs `playwright: {mode: novnc}` (this session's browser has no display)")
    if control and pw.get("allow_control") is not True:
        raise _fail("--control needs `allow_control: true` in the session's playwright settings")
    if not _running(runtime, container):
        raise _fail(f"{container} is not running — `glove up` first")
    r = subprocess.run([runtime, "exec", container, "cat", f"/tmp/vnc/{'full' if control else 'view'}"],
                       capture_output=True, text=True)
    if r.returncode != 0 or not r.stdout.strip():
        raise _fail(f"cannot read the VNC password from {container}")
    try:
        asyncio.run(_serve(runtime, container, r.stdout.strip(), control=control, open_browser=not no_open))
    except KeyboardInterrupt:
        console.print("closed")


@app.command("status")
def status(directory: Path | None = DIR_OPT) -> None:
    """The browser mode and whether its sidecar is running."""
    runtime, container, pw = _session(directory)
    mode = pw.get("mode", "headless")
    if mode == "host":
        console.print("mode host: the browser runs on this machine (host services)")
        return
    state = "running" if _running(runtime, container) else "not running"
    console.print(f"mode {mode}: {container} {state}")
