"""Compose extension image layers into a derived harness image.

The minimal base (``glove/<harness>:<ver>``) is built from the harness's own
Dockerfile. When extensions contribute image layers or Pi extensions, glove
composes a *derived* image: ``FROM <base>`` plus each contribution, in
extension order. Its tag is content-addressed — a hash of the rendered
Dockerfile and every staged file — so any change to a layer, a setting that
selects one, or an asset yields a new image, and "not selected" means "not in
the image".
"""

from __future__ import annotations

import hashlib
import os
import shlex
import shutil
from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING

from .harness import HarnessProfile, adapter_call

if TYPE_CHECKING:
    from .extensions import Composition
    from .toolchains import Toolchain

LAYER_KEYS = frozenset({"apt", "pip", "npm", "copy", "run"})
# Never staged or hashed: host build output and caches (a host node_modules or
# .venv is the wrong OS/arch, and would poison the content hash).
STAGE_IGNORE = ("node_modules", "__pycache__", ".venv", ".git")


def _q(pkgs) -> str:
    """Shell-quote package tokens (pip version specifiers carry `<`/`>`/`;`)."""
    return " ".join(shlex.quote(str(p)) for p in pkgs)


def _apt_bootstrap(probe: str, pkgs) -> str:
    """Apt-install `pkgs` unless the base image already has `probe`."""
    return (f"RUN command -v {probe} >/dev/null || (apt-get update "
            f"&& apt-get install -y --no-install-recommends {_q(pkgs)} "
            "&& rm -rf /var/lib/apt/lists/*)")


def staged_name(ext: str, src: Path) -> str:
    """Build-context path a source is staged at, namespaced by extension."""
    return f"{ext}/{src.name}"


def _layer_lines(ext: str, layer: dict, profile: HarnessProfile, ext_dir: Path) -> tuple[list[str], list[Path]]:
    unknown = set(layer) - LAYER_KEYS
    if unknown:
        raise ValueError(f"extension {ext!r}: unknown image layer keys {sorted(unknown)}")
    lines: list[str] = []
    sources: list[Path] = []
    if layer.get("apt"):
        lines.append(
            "RUN apt-get update "
            f"&& apt-get install -y --no-install-recommends {_q(layer['apt'])} "
            "&& rm -rf /var/lib/apt/lists/*"
        )
    if layer.get("pip"):
        if profile.pip_install is None:
            raise ValueError(
                f"harness {profile.name!r} has no Python installer but extension {ext!r} "
                f"requests pip packages {list(layer['pip'])}"
            )
        if profile.pip_bootstrap:
            lines.append(_apt_bootstrap("pip3", profile.pip_bootstrap))
        lines.append(f"RUN {' '.join(profile.pip_install)} {_q(layer['pip'])}")
    if layer.get("npm"):
        lines.append(f"RUN npm install -g {_q(layer['npm'])}")
    for src, dst in layer.get("copy") or []:
        path = (ext_dir / src).resolve()
        if not path.exists() or not path.is_relative_to(ext_dir):
            raise ValueError(f"extension {ext!r}: image copy source {src!r} must exist inside the extension")
        sources.append(path)
        lines.append(f"COPY {staged_name(ext, path)} {dst}")
    for cmd in layer.get("run") or []:
        lines.append(f"RUN {cmd}")
    return lines, sources


def render_dockerfile(
    base_tag: str, profile: HarnessProfile, comp: Composition, toolchains: Sequence[Toolchain] = (),
) -> tuple[str | None, list[tuple[str, Path]]]:
    """(Dockerfile text, [(ext, staged source)]) for the derived image: the
    extensions' contributions, then the session's `toolchains` (last, so their
    PATH never affects an extension's build step). (None, []) when nothing
    contributes: the session runs the base image."""
    lines = [f"# Generated by glove — derived image: {base_tag} + extensions.", f"FROM {base_tag}"]
    staged: list[tuple[str, Path]] = []
    for ext, layer in comp.image_layers:
        a = comp.by_name(ext)
        lines.append(f"# extension: {ext}")
        body, sources = _layer_lines(ext, layer, profile, a.manifest.path)
        lines += body
        staged += [(ext, s) for s in sources]
    # the harness's own image contributions (e.g. Pi's `-e` extensions)
    body, sources = adapter_call(profile, "image_lines", comp, default=([], []))
    lines += body
    staged += sources
    for ext, src, dest in comp.skills:
        if src is not None:
            staged.append((ext, src))
            lines.append(f"# extension: {ext} (skill)")
            lines.append(f"COPY {staged_name(ext, src)} {dest}")
    if toolchains:
        from .toolchains import dockerfile_lines

        body, sources = dockerfile_lines(toolchains)
        lines += body
        staged += sources
    if len(lines) == 2:
        return None, []
    seen: dict[str, Path] = {}
    for ext, src in staged:  # staged by name: two sources must not share one
        other = seen.setdefault(staged_name(ext, src), src)
        if other != src:
            raise ValueError(f"extension {ext!r}: {src} and {other} would both stage as {staged_name(ext, src)!r}; "
                             "rename one")
    return "\n".join(lines) + "\n", staged


def _stage_files(src: Path) -> list[Path]:
    """The files (and symlinks, never followed) `stage_context` copies from a
    directory, sorted; STAGE_IGNORE trees are pruned, not walked."""
    out: list[Path] = []
    for root, dirs, files in os.walk(src):
        dirs[:] = [d for d in dirs if d not in STAGE_IGNORE]
        out += [Path(root, d) for d in dirs if Path(root, d).is_symlink()]
        out += [Path(root, f) for f in files if f not in STAGE_IGNORE]
    return sorted(out)


def content_hash(dockerfile: str, staged: list[tuple[str, Path]]) -> str:
    h = hashlib.sha256(dockerfile.encode())
    for ext, src in staged:
        for f in [src] if src.is_file() else _stage_files(src):
            h.update(f"{ext}/{f.relative_to(src.parent)}".encode())
            # a symlink is staged as a link (never followed out of its tree)
            h.update(f"-> {os.readlink(f)}".encode() if f.is_symlink() else f.read_bytes())
    return h.hexdigest()[:10]


def stage_context(dest: Path, staged: list[tuple[str, Path]]) -> None:
    """Copy every staged source into the build context ``dest``."""
    for ext, src in staged:
        target = dest / staged_name(ext, src)
        target.parent.mkdir(parents=True, exist_ok=True)
        if src.is_dir():
            shutil.copytree(src, target, dirs_exist_ok=True, symlinks=True,
                            ignore=shutil.ignore_patterns(*STAGE_IGNORE))
        else:
            shutil.copy2(src, target)
