"""Compose extension image layers into a derived harness image.

The minimal base (``glove/<harness>:<ver>``) is built from the harness's own
Dockerfile. When extensions contribute image layers or Pi extensions, glove
composes a *derived* image: ``FROM <base>`` plus each contribution, in
extension order. Its tag is content-addressed — a hash of the rendered
Dockerfile and every staged file — so any change to a layer, a setting that
selects one, or an asset yields a new image, and "not selected" means "not in
the image".
"""

from __future__ import annotations

import hashlib
import os
import shlex
import shutil
from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING

from .harness import HarnessProfile

if TYPE_CHECKING:
    from .extensions import Composition
    from .toolchains import Toolchain

LAYER_KEYS = frozenset({"apt", "pip", "npm", "copy", "run"})
# Never staged or hashed: host build output and caches (a host node_modules or
# .venv is the wrong OS/arch, and would poison the content hash).
STAGE_IGNORE = ("node_modules", "__pycache__", ".venv", ".git")


def _q(pkgs) -> str:
    """Shell-quote package tokens (pip version specifiers carry `<`/`>`/`;`)."""
    return " ".join(shlex.quote(str(p)) for p in pkgs)


def _staged(ext: str, src: Path) -> str:
    """Build-context path a source is staged at, namespaced by extension."""
    return f"{ext}/{src.name}"


def _layer_lines(ext: str, layer: dict, profile: HarnessProfile, ext_dir: Path) -> tuple[list[str], list[Path]]:
    unknown = set(layer) - LAYER_KEYS
    if unknown:
        raise ValueError(f"extension {ext!r}: unknown image layer keys {sorted(unknown)}")
    lines: list[str] = []
    sources: list[Path] = []
    if layer.get("apt"):
        lines.append(
            "RUN apt-get update "
            f"&& apt-get install -y --no-install-recommends {_q(layer['apt'])} "
            "&& rm -rf /var/lib/apt/lists/*"
        )
    if layer.get("pip"):
        if profile.pip_install is None:
            raise ValueError(
                f"harness {profile.name!r} has no Python installer but extension {ext!r} "
                f"requests pip packages {list(layer['pip'])}"
            )
        if profile.pip_bootstrap:
            lines.append(
                "RUN command -v pip3 >/dev/null || (apt-get update "
                f"&& apt-get install -y --no-install-recommends {_q(profile.pip_bootstrap)} "
                "&& rm -rf /var/lib/apt/lists/*)"
            )
        lines.append(f"RUN {' '.join(profile.pip_install)} {_q(layer['pip'])}")
    if layer.get("npm"):
        lines.append(f"RUN npm install -g {_q(layer['npm'])}")
    for src, dst in layer.get("copy") or []:
        path = (ext_dir / src).resolve()
        if not path.exists() or not path.is_relative_to(ext_dir):
            raise ValueError(f"extension {ext!r}: image copy source {src!r} must exist inside the extension")
        sources.append(path)
        lines.append(f"COPY {_staged(ext, path)} {dst}")
    for cmd in layer.get("run") or []:
        lines.append(f"RUN {cmd}")
    return lines, sources


def render_dockerfile(
    base_tag: str, profile: HarnessProfile, comp: Composition, toolchains: Sequence[Toolchain] = (),
) -> tuple[str, list[tuple[str, Path]]]:
    """(Dockerfile text, [(ext, staged source)]) for the derived image: the
    extensions' contributions, then the session's `toolchains` (last, so their
    PATH never affects an extension's build step)."""
    lines = [f"# Generated by glove — derived image: {base_tag} + extensions.", f"FROM {base_tag}"]
    staged: list[tuple[str, Path]] = []
    for ext, layer in comp.image_layers:
        a = comp.by_name(ext)
        lines.append(f"# extension: {ext}")
        body, sources = _layer_lines(ext, layer, profile, a.manifest.path)
        lines += body
        staged += [(ext, s) for s in sources]
    for ext, src in comp.pi_extensions:
        dest = comp.pi_extension_dest(ext, src)
        staged.append((ext, src))
        lines.append(f"# extension: {ext} (Pi extension)")
        lines.append(f"COPY {_staged(ext, src)} {dest}")
        if (src / "package.json").is_file():
            lines.append(f"RUN cd {dest} && npm install --no-audit --no-fund")
    for ext, src, dest in comp.pi_skills:
        if src is not None:
            staged.append((ext, src))
            lines.append(f"# extension: {ext} (Pi skill)")
            lines.append(f"COPY {_staged(ext, src)} {dest}")
    if toolchains:
        from .toolchains import dockerfile_lines

        body, sources = dockerfile_lines(list(toolchains))
        lines += body
        staged += sources
    seen: dict[str, Path] = {}
    for ext, src in staged:  # staged by name: two sources must not share one
        other = seen.setdefault(_staged(ext, src), src)
        if other != src:
            raise ValueError(f"extension {ext!r}: {src} and {other} would both stage as {_staged(ext, src)!r}; "
                             "rename one")
    return "\n".join(lines) + "\n", staged


def content_hash(dockerfile: str, staged: list[tuple[str, Path]]) -> str:
    h = hashlib.sha256(dockerfile.encode())
    for ext, src in staged:
        files = [src] if src.is_file() else sorted(p for p in src.rglob("*") if p.is_file() or p.is_symlink())
        for f in files:
            if any(part in STAGE_IGNORE for part in f.relative_to(src.parent).parts):
                continue
            h.update(f"{ext}/{f.relative_to(src.parent)}".encode())
            # a symlink is staged as a link (never followed out of its tree)
            h.update(f"-> {os.readlink(f)}".encode() if f.is_symlink() else f.read_bytes())
    return h.hexdigest()[:10]


def stage_context(dest: Path, staged: list[tuple[str, Path]]) -> None:
    """Copy every staged source into the build context ``dest``."""
    for ext, src in staged:
        target = dest / _staged(ext, src)
        target.parent.mkdir(parents=True, exist_ok=True)
        if src.is_dir():
            shutil.copytree(src, target, dirs_exist_ok=True, symlinks=True,
                            ignore=shutil.ignore_patterns(*STAGE_IGNORE))
        else:
            shutil.copy2(src, target)
