"""Vendored seccomp profiles for the docker/podman runtimes (PLAN.md §3.4).

- ``default.json`` — Docker/moby's current default seccomp profile, vendored
  verbatim so glove's hardening is identical across Docker versions. Applied
  explicitly to the harness so it shows up in ``docker inspect`` and pins
  behavior. Source: https://github.com/moby/profiles/blob/main/seccomp/default.json
  (captured 2026-09-03; see docs/research for the exact engine/version).
- ``nested-userns.json`` — the *surgical* relaxation of ``default.json`` used
  only when ``enforcer: srt`` (bubblewrap needs unprivileged user namespaces).
  Generated by ``make_profile.py``; regenerate with
  ``python -m glove.runtimes.seccomp.make_profile``.
"""

from __future__ import annotations

from pathlib import Path

SECCOMP_DIR = Path(__file__).parent
DEFAULT_PROFILE = SECCOMP_DIR / "default.json"
NESTED_USERNS_PROFILE = SECCOMP_DIR / "nested-userns.json"


def default_profile_path() -> str:
    """Absolute path to the vendored default seccomp profile."""
    return str(DEFAULT_PROFILE)


def nested_userns_profile_path() -> str:
    """Absolute path to the surgically relaxed (srt) seccomp profile."""
    return str(NESTED_USERNS_PROFILE)
