"""Render enabled plugins into a derived Dockerfile + build context.

The minimal base image (``glove/<harness>:<ver>``) is built from the harness's
own Dockerfile. When a session enables plugins (or requests extra apt/pip
packages), glove composes a *derived* image: ``FROM <base>`` plus one set of
layers per plugin. The derived image is what the session actually runs; the base
stays cached and untouched, so unrelated plugin combinations reuse it.

Keeping plugin contributions as separate layers on top of the base — rather than
editing each harness Dockerfile — is what makes "off = not in the image" hold:
no plugin ⇒ no derived layer ⇒ the plain base runs.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from ..harness import HarnessProfile
from .base import ImageLayer, Plugin


def _render_layer(layer: ImageLayer, profile: HarnessProfile) -> list[str]:
    """Dockerfile lines for one image layer (Debian-derived bases)."""
    lines: list[str] = []
    if layer.apt:
        pkgs = " ".join(layer.apt)
        lines.append(
            "RUN apt-get update "
            f"&& apt-get install -y --no-install-recommends {pkgs} "
            "&& rm -rf /var/lib/apt/lists/*"
        )
    if layer.pip:
        if profile.pip_install is None:
            raise ValueError(
                f"harness {profile.name!r} has no Python installer but a plugin "
                f"requests pip packages {list(layer.pip)}"
            )
        installer = " ".join(profile.pip_install)
        lines.append(f"RUN {installer} {' '.join(layer.pip)}")
    if layer.npm:
        lines.append(f"RUN npm install -g {' '.join(layer.npm)}")
    for src, dst in layer.copy:
        # src is staged into the build context under its basename (see
        # stage_context); COPY references that staged name.
        lines.append(f"COPY {Path(src).name} {dst}")
    for cmd in layer.run:
        lines.append(f"RUN {cmd}")
    return lines


def render_dockerfile(
    base_tag: str, profile: HarnessProfile, plugins: list[Plugin]
) -> str:
    """The derived Dockerfile: ``FROM base_tag`` + each plugin's layers."""
    lines = [
        f"# Generated by glove — derived image: {base_tag} + plugins "
        f"[{', '.join(p.name for p in plugins)}].",
        f"FROM {base_tag}",
    ]
    for plugin in plugins:
        layers = plugin.layers_for(profile.name)
        if not layers:
            continue
        lines.append(f"# plugin: {plugin.name} — {plugin.summary}")
        for layer in layers:
            lines.extend(_render_layer(layer, profile))
    return "\n".join(lines) + "\n"


def stage_context(dest: Path, profile: HarnessProfile, plugins: list[Plugin]) -> None:
    """Copy every plugin ``copy`` source into the build context ``dest``.

    Sources are staged under their basename, matching the ``COPY`` lines
    ``render_dockerfile`` emits. ``dest`` must already exist.
    """
    for plugin in plugins:
        for layer in plugin.layers_for(profile.name):
            for src, _dst in layer.copy:
                src_path = Path(src)
                target = dest / src_path.name
                if src_path.is_dir():
                    shutil.copytree(src_path, target, dirs_exist_ok=True)
                else:
                    shutil.copy2(src_path, target)
